---
title: "supp_separate_histograms-with_butteflies"
author: "Filip Wierzbicki"
date: "11/29/2022"
output: rmarkdown::github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, eval=TRUE}

library(dplyr)
library(ggplot2)
library(ggpubr)

th=5

b1<-read.table("/Volumes/Temp3/filip/trap_model/butterfly/filtered-reads/map/output-V3/TE/Canton-S_w500.txt")
names(b1)<-c("TE","chr","start","end","ls","la","rs","ra","strain")
b2<-read.table("/Volumes/Temp3/filip/trap_model/butterfly/filtered-reads/map/output-V3/TE/DGRP-732_w500.txt")
names(b2)<-c("TE","chr","start","end","ls","la","rs","ra","strain")
b3<-read.table("/Volumes/Temp3/filip/trap_model/butterfly/filtered-reads/map/output-V3/TE/Iso1_w500.txt")
names(b3)<-c("TE","chr","start","end","ls","la","rs","ra","strain")
b4<-read.table("/Volumes/Temp3/filip/trap_model/butterfly/filtered-reads/map/output-V3/TE/Oregon-R_w500.txt")
names(b4)<-c("TE","chr","start","end","ls","la","rs","ra","strain")
b5<-read.table("/Volumes/Temp3/filip/trap_model/butterfly/filtered-reads/map/output-V3/TE/Pi2_w500.txt")
names(b5)<-c("TE","chr","start","end","ls","la","rs","ra","strain")


a1<-read.table("/Users/filipwierzbicki/Desktop/trap_model/analysis/abu/cusco_tas/gapped_combined-distinct/Canton-S_gapped_cusco_tas_summary.forR")
a2<-read.table("/Users/filipwierzbicki/Desktop/trap_model/analysis/abu/cusco_tas/gapped_combined-distinct/DGRP-732_gapped_cusco_tas_summary.forR")
a3<-read.table("/Users/filipwierzbicki/Desktop/trap_model/analysis/abu/cusco_tas/gapped_combined-distinct/Iso1_gapped_cusco_tas_summary.forR")
a4<-read.table("/Users/filipwierzbicki/Desktop/trap_model/analysis/abu/cusco_tas/gapped_combined-distinct/Oregon-R_gapped_cusco_tas_summary.forR")
a5<-read.table("/Users/filipwierzbicki/Desktop/trap_model/analysis/abu/cusco_tas/gapped_combined-distinct/Pi2_gapped_cusco_tas_summary.forR")
names(a1)<-c("count","strain","TE","region")
names(a2)<-c("count","strain","TE","region")
names(a3)<-c("count","strain","TE","region")
names(a4)<-c("count","strain","TE","region")
names(a5)<-c("count","strain","TE","region")

c1<-read.table("/Users/filipwierzbicki/Desktop/trap_model/analysis/abu/cusco_tas/gapped_combined-distinct/Canton-S_cluster.bed")
names(c1)<-c("chr","start","end","cluster","ig","ir")
c2<-read.table("/Users/filipwierzbicki/Desktop/trap_model/analysis/abu/cusco_tas/gapped_combined-distinct/DGRP-732_cluster.bed")
names(c2)<-c("chr","start","end","cluster","ig","ir")
c3<-read.table("/Users/filipwierzbicki/Desktop/trap_model/analysis/abu/cusco_tas/gapped_combined-distinct/Iso1_cluster.bed")
names(c3)<-c("chr","start","end","cluster","ig","ir")
c4<-read.table("/Users/filipwierzbicki/Desktop/trap_model/analysis/abu/cusco_tas/gapped_combined-distinct/Oregon-R_cluster.bed")
names(c4)<-c("chr","start","end","cluster","ig","ir")
c5<-read.table("/Users/filipwierzbicki/Desktop/trap_model/analysis/abu/cusco_tas/gapped_combined-distinct/Pi2_cluster.bed")
names(c5)<-c("chr","start","end","cluster","ig","ir")

c1$start<-c1$start+1
c1$end<-c1$end+1

c2$start<-c2$start+1
c2$end<-c2$end+1

c3$start<-c3$start+1
c3$end<-c3$end+1

c4$start<-c4$start+1
c4$end<-c4$end+1

c5$start<-c5$start+1
c5$end<-c5$end+1


b1$id<-paste(b1$TE,b1$chr,b1$start,b1$end,sep = "_")
b2$id<-paste(b2$TE,b2$chr,b2$start,b2$end,sep = "_")
b3$id<-paste(b3$TE,b3$chr,b3$start,b3$end,sep = "_")
b4$id<-paste(b4$TE,b4$chr,b4$start,b4$end,sep = "_")
b5$id<-paste(b5$TE,b5$chr,b5$start,b5$end,sep = "_")

###
#excluding signatures from clusters: 
ic=b1[FALSE,]

for(i in 1:nrow(b1)) {
  row <- b1[i,]
  
  for(k in 1:nrow(c1)){
    line <- c1[k,]
    if ((line$chr==row$chr && line$start<=row$start&&row$start<=line$end)||(line$chr==row$chr && line$start<=row$end&&row$end<=line$end)){
      ic[nrow(ic) + 1,] <- row
      break
    }
    
  }
}

nc<-anti_join(b1,ic,by="id")

ic=nc[FALSE,]

for(i in 1:nrow(nc)) {
  row <- nc[i,]
  if (row$la>=th && row$rs>=th){
    ic[nrow(ic) + 1,] <- row
  }
}


for (sid in unique(ic$TE)) { 
  i <- ic$TE == sid
  x = nrow(subset(ic,ic$TE==sid))
  ic$butterfly[i] = x
}
bfs<-subset(ic,select = c("TE","butterfly","strain"))
bfs<-unique(bfs)
ac<-subset(a1,region=="cluster")
ac<-subset(ac,select=c("TE","count"))
TE1<-full_join(bfs,ac,by="TE")
anc<-subset(a1,region!="cluster")
anc<-subset(anc,select=c("TE","count"))

for (sid in unique(anc$TE)) { 
  i <- anc$TE == sid
  a = sum(anc$count[i])
  anc$sum[i] = a
}
anc<-subset(anc,select=c("TE","sum"))
anc<-unique(anc)

names(anc)<-c("TE","rest")
TE1<-full_join(TE1,anc,by="TE")
TE1$strain<-c("Canton-S")

#

ic=b2[FALSE,]

for(i in 1:nrow(b2)) {
  row <- b2[i,]
  
  for(k in 1:nrow(c2)){
    line <- c2[k,]
    if ((line$chr==row$chr && line$start<=row$start&&row$start<=line$end)||(line$chr==row$chr && line$start<=row$end&&row$end<=line$end)){
      ic[nrow(ic) + 1,] <- row
      break
    }
    
  }
}

nc<-anti_join(b2,ic,by="id")

ic=nc[FALSE,]

for(i in 1:nrow(nc)) {
  row <- nc[i,]
  if (row$la>=th && row$rs>=th){
    ic[nrow(ic) + 1,] <- row
  }
}

for (sid in unique(ic$TE)) { 
  i <- ic$TE == sid
  x = nrow(subset(ic,ic$TE==sid))
  ic$butterfly[i] = x
}
bfs<-subset(ic,select = c("TE","butterfly","strain"))
bfs<-unique(bfs)
ac<-subset(a2,region=="cluster")
ac<-subset(ac,select=c("TE","count"))
TE2<-full_join(bfs,ac,by="TE")
anc<-subset(a2,region!="cluster")
anc<-subset(anc,select=c("TE","count"))

for (sid in unique(anc$TE)) { 
  i <- anc$TE == sid
  a = sum(anc$count[i])
  anc$sum[i] = a
}
anc<-subset(anc,select=c("TE","sum"))
anc<-unique(anc)

names(anc)<-c("TE","rest")
TE2<-full_join(TE2,anc,by="TE")
TE2$strain<-c("DGRP-732")

#

ic=b3[FALSE,]

for(i in 1:nrow(b3)) {
  row <- b3[i,]
  
  for(k in 1:nrow(c3)){
    line <- c3[k,]
    if ((line$chr==row$chr && line$start<=row$start&&row$start<=line$end)||(line$chr==row$chr && line$start<=row$end&&row$end<=line$end)){
      ic[nrow(ic) + 1,] <- row
      break
    }
    
  }
}

nc<-anti_join(b3,ic,by="id")

ic=nc[FALSE,]

for(i in 1:nrow(nc)) {
  row <- nc[i,]
  if (row$la>=th && row$rs>=th){
    ic[nrow(ic) + 1,] <- row
  }
}

for (sid in unique(ic$TE)) { 
  i <- ic$TE == sid
  x = nrow(subset(ic,ic$TE==sid))
  ic$butterfly[i] = x
}
bfs<-subset(ic,select = c("TE","butterfly","strain"))
bfs<-unique(bfs)
ac<-subset(a3,region=="cluster")
ac<-subset(ac,select=c("TE","count"))
TE3<-full_join(bfs,ac,by="TE")
anc<-subset(a3,region!="cluster")
anc<-subset(anc,select=c("TE","count"))

for (sid in unique(anc$TE)) { 
  i <- anc$TE == sid
  a = sum(anc$count[i])
  anc$sum[i] = a
}
anc<-subset(anc,select=c("TE","sum"))
anc<-unique(anc)

names(anc)<-c("TE","rest")
TE3<-full_join(TE3,anc,by="TE")
TE3$strain<-c("Iso1")

#

ic=b4[FALSE,]

for(i in 1:nrow(b4)) {
  row <- b4[i,]
  
  for(k in 1:nrow(c4)){
    line <- c4[k,]
    if ((line$chr==row$chr && line$start<=row$start&&row$start<=line$end)||(line$chr==row$chr && line$start<=row$end&&row$end<=line$end)){
      ic[nrow(ic) + 1,] <- row
      break
    }
    
  }
}

nc<-anti_join(b4,ic,by="id")

ic=nc[FALSE,]

for(i in 1:nrow(nc)) {
  row <- nc[i,]
  if (row$la>=th && row$rs>=th){
    ic[nrow(ic) + 1,] <- row
  }
}

for (sid in unique(ic$TE)) { 
  i <- ic$TE == sid
  x = nrow(subset(ic,ic$TE==sid))
  ic$butterfly[i] = x
}
bfs<-subset(ic,select = c("TE","butterfly","strain"))
bfs<-unique(bfs)
ac<-subset(a4,region=="cluster")
ac<-subset(ac,select=c("TE","count"))
TE4<-full_join(bfs,ac,by="TE")
anc<-subset(a4,region!="cluster")
anc<-subset(anc,select=c("TE","count"))

for (sid in unique(anc$TE)) { 
  i <- anc$TE == sid
  a = sum(anc$count[i])
  anc$sum[i] = a
}
anc<-subset(anc,select=c("TE","sum"))
anc<-unique(anc)

names(anc)<-c("TE","rest")
TE4<-full_join(TE4,anc,by="TE")
TE4$strain<-c("Oregon-R")

#

ic=b5[FALSE,]

for(i in 1:nrow(b5)) {
  row <- b5[i,]
  
  for(k in 1:nrow(c5)){
    line <- c5[k,]
    if ((line$chr==row$chr && line$start<=row$start&&row$start<=line$end)||(line$chr==row$chr && line$start<=row$end&&row$end<=line$end)){
      ic[nrow(ic) + 1,] <- row
      break
    }
    
  }
}

nc<-anti_join(b5,ic,by="id")

ic=nc[FALSE,]

for(i in 1:nrow(nc)) {
  row <- nc[i,]
  if (row$la>=th && row$rs>=th){
    ic[nrow(ic) + 1,] <- row
  }
}

for (sid in unique(ic$TE)) { 
  i <- ic$TE == sid
  x = nrow(subset(ic,ic$TE==sid))
  ic$butterfly[i] = x
}
bfs<-subset(ic,select = c("TE","butterfly","strain"))
bfs<-unique(bfs)
ac<-subset(a5,region=="cluster")
ac<-subset(ac,select=c("TE","count"))
TE5<-full_join(bfs,ac,by="TE")
anc<-subset(a5,region!="cluster")
anc<-subset(anc,select=c("TE","count"))

for (sid in unique(anc$TE)) { 
  i <- anc$TE == sid
  a = sum(anc$count[i])
  anc$sum[i] = a
}
anc<-subset(anc,select=c("TE","sum"))
anc<-unique(anc)

names(anc)<-c("TE","rest")
TE5<-full_join(TE5,anc,by="TE")
TE5$strain<-c("Pi2")



#######
###For population frequency Info based on Kofler et al. 2015 PLOS Genetics
info1<-read.table("/Users/filipwierzbicki/Desktop/evolution_cluster/temp/TEfamInfo_correct")
names(info1)<-c("name","TE","order","AF","popins")

###exclude somatically regulated TEs based on Malone et al. 2009 Cell
info1<-subset(info1,name!="gypsy10"&name!="gypsy"&name!="ZAM"&name!="gtwin"&name!="gypsy5"&name!="Tabor")

info<-subset(info1,select=c("TE","AF"))
info$AF<-round(info$AF,digits = 1)

infoP<-subset(info1,select=c("name","AF"))
infoP$AF<-round(infoP$AF,digits = 1)
names(infoP)<-c("TE","AF")



#average across assemblies:
t<-rbind(TE1,TE2,TE3,TE4,TE5)


####
t<-left_join(t,info,by="TE")

#including AF threshold
t<-subset(t,AF!="NA")##remove missing AFs
t<-subset(t,AF<=0.2)

t[is.na(t)] <- 0
t$sum<-t$butterfly+t$count
tbut<-subset(t,select=c("TE","sum","strain"))
names(tbut)<-c("TE","cluster","strain")
tclu<-subset(t,select=c("TE","count","strain"))
names(tclu)<-c("TE","cluster","strain")

tbut$id3<-paste(tbut$cluster,tbut$strain,sep="_")
for (sid in unique(tbut$id3)) { 
  i <- tbut$id3 == sid
  a = nrow(subset(tbut,id3==sid))
  tbut$inds[i] = a
}

tbut<-subset(tbut,select=c("cluster","inds","strain"))
tbut<-unique(tbut)

for (sid in unique(tbut$strain)) { 
  i <- tbut$strain == sid
  tbut$indsrel[i]<-tbut$inds[i]/sum(tbut$inds[i])
}


tclu$id3<-paste(tclu$cluster,tclu$strain,sep="_")
for (sid in unique(tclu$id3)) { 
  i <- tclu$id3 == sid
  a = nrow(subset(tclu,id3==sid))
  tclu$inds[i] = a
}

tclu<-subset(tclu,select=c("cluster","inds","strain"))
tclu<-unique(tclu)

for (sid in unique(tclu$strain)) { 
  i <- tclu$strain == sid
  tclu$indsrel[i]<-tclu$inds[i]/sum(tclu$inds[i])
}


dfc1<-data.frame(cluster = 0:30,strain="Canton-S")
dfc2<-data.frame(cluster = 0:30,strain="DGRP-732")
dfc3<-data.frame(cluster = 0:30,strain="Iso1")
dfc4<-data.frame(cluster = 0:30,strain="Oregon-R")
dfc5<-data.frame(cluster = 0:30,strain="Pi2")
dfc<-rbind(dfc1,dfc2,dfc3,dfc4,dfc5)
dfc$id<-paste(dfc$cluster,dfc$strain,sep = "_")

tbut$id<-paste(tbut$cluster,tbut$strain,sep = "_")
tclu$id<-paste(tclu$cluster,tclu$strain,sep = "_")

tbut<-left_join(dfc,tbut,by="id")
tclu<-left_join(dfc,tclu,by="id")

tbut$type<-c("with-butterfly")
tclu$type<-c("cluster-only")

t<-rbind(tbut,tclu)
t[is.na(t)] <- 0
ghis<-ggplot(t, aes(x=cluster.x, y=indsrel,fill=type))+ geom_bar(stat="identity",position = "dodge")+facet_wrap(~strain.x,ncol = 5)+ylab("frequency of individuals")+xlab("number of cluster insertions")+
  theme_bw()+theme(legend.position="right")+scale_fill_discrete(name=NULL)#+ coord_cartesian(xlim = c(0, 30))#, expand = FALSE#+xlim(-1,31)


plot(ghis)
ggsave("/Users/filipwierzbicki/Desktop/trap_model/analysis/abu/figures/supp_butterfly-histo.pdf",width=12,height=3)
ggsave("/Users/filipwierzbicki/Desktop/trap_model/analysis/abu/figures/supp_butterfly-histo.png",width=12,height=3)

```

